-- Inserir dados na tabela DEPARTAMENTOS
INSERT INTO USR_GESTAO_RH.DEPARTAMENTOS (NOME, LOCALIZACAO) 
VALUES ('TI', 'São Paulo');

INSERT INTO USR_GESTAO_RH.DEPARTAMENTOS (NOME, LOCALIZACAO) 
VALUES ('Recursos Humanos', 'Rio de Janeiro');

INSERT INTO USR_GESTAO_RH.DEPARTAMENTOS (NOME, LOCALIZACAO) 
VALUES ('Financeiro', 'Curitiba');

-- Inserir dados na tabela FUNCIONARIOS
INSERT INTO USR_GESTAO_RH.FUNCIONARIOS (NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO, DEPARTAMENTO_ID)
VALUES ('Montival Lucas', TO_DATE('2003-05-09', 'YYYY-MM-DD'), 'Analista Financeiro', 7000.00, TO_DATE('2023-09-15', 'YYYY-MM-DD'), 1);

INSERT INTO USR_GESTAO_RH.FUNCIONARIOS (NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO, DEPARTAMENTO_ID)
VALUES ('Yuji Ihara', TO_DATE('1990-03-20', 'YYYY-MM-DD'), 'Engenheiro', 5000.00, TO_DATE('2023-07-01', 'YYYY-MM-DD'), 1);

INSERT INTO USR_GESTAO_RH.FUNCIONARIOS (NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO, DEPARTAMENTO_ID)
VALUES ('Bruno Oliveira', TO_DATE('1985-11-30', 'YYYY-MM-DD'), 'Gerente de RH', 6000.00, TO_DATE('2022-03-25', 'YYYY-MM-DD'), 2);

-- Inserir dados na tabela AVALIACOES_DESEMPENHO
INSERT INTO USR_GESTAO_RH.AVALIACOES_DESEMPENHO (FUNCIONARIO_ID, DATA_AVALIACAO, NOTA, COMENTARIOS)
VALUES (1, TO_DATE('2023-10-01', 'YYYY-MM-DD'), 4.8, 'Excelente desempenho.');

INSERT INTO USR_GESTAO_RH.AVALIACOES_DESEMPENHO (FUNCIONARIO_ID, DATA_AVALIACAO, NOTA, COMENTARIOS)
VALUES (2, TO_DATE('2023-11-05', 'YYYY-MM-DD'), 4.5, 'Bom trabalho, pode melhorar.');

INSERT INTO USR_GESTAO_RH.AVALIACOES_DESEMPENHO (FUNCIONARIO_ID, DATA_AVALIACAO, NOTA, COMENTARIOS)
VALUES (3, TO_DATE('2023-12-01', 'YYYY-MM-DD'), 4.9, 'Desempenho exemplar.');

-- Inserir dados na tabela FOLHA_PAGAMENTO
INSERT INTO USR_GESTAO_RH.FOLHA_PAGAMENTO (FUNCIONARIO_ID, DATA_PAGAMENTO, SALARIO_BRUTO, DESCONTOS, SALARIO_LIQUIDO)
VALUES (1, TO_DATE('2023-09-30', 'YYYY-MM-DD'), 4000.00, 500.00, 3500.00);

INSERT INTO USR_GESTAO_RH.FOLHA_PAGAMENTO (FUNCIONARIO_ID, DATA_PAGAMENTO, SALARIO_BRUTO, DESCONTOS, SALARIO_LIQUIDO)
VALUES (2, TO_DATE('2023-09-30', 'YYYY-MM-DD'), 5000.00, 600.00, 4400.00);

INSERT INTO USR_GESTAO_RH.FOLHA_PAGAMENTO (FUNCIONARIO_ID, DATA_PAGAMENTO, SALARIO_BRUTO, DESCONTOS, SALARIO_LIQUIDO)
VALUES (3, TO_DATE('2023-09-30', 'YYYY-MM-DD'), 6000.00, 800.00, 5200.00);



-- Verifique os dados inseridos nas tabelas
SELECT * FROM USR_GESTAO_RH.DEPARTAMENTOS;
SELECT * FROM USR_GESTAO_RH.FUNCIONARIOS;
SELECT * FROM USR_GESTAO_RH.AVALIACOES_DESEMPENHO;
SELECT * FROM USR_GESTAO_RH.FOLHA_PAGAMENTO;
