------- Criação das Tabelas ----------
------DEPARTAMENTOS--------
CREATE TABLE USR_GESTAO_RH.DEPARTAMENTOS (
    DEPARTAMENTO_ID NUMBER(38, 0) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    LOCALIZACAO VARCHAR2(100),
    CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY (DEPARTAMENTO_ID)
);
-- Sequência para DEPARTAMENTO_ID
CREATE SEQUENCE DEPARTAMENTO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_DEPARTAMENTO_ID
BEFORE INSERT ON USR_GESTAO_RH.DEPARTAMENTOS
FOR EACH ROW
WHEN (NEW.DEPARTAMENTO_ID IS NULL)
BEGIN
   :NEW.DEPARTAMENTO_ID := DEPARTAMENTO_SEQ.NEXTVAL;
END;
/


--------FUNCIONARIOS--------
CREATE TABLE USR_GESTAO_RH.FUNCIONARIOS (
    FUNCIONARIO_ID NUMBER(38, 0) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    CARGO VARCHAR2(100),
    SALARIO NUMBER(10, 2),
    DATA_ADMISSAO DATE,
    DEPARTAMENTO_ID NUMBER(38, 0),
    CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (FUNCIONARIO_ID),
    CONSTRAINT FK_FUNCIONARIOS_DEPARTAMENTOS FOREIGN KEY (DEPARTAMENTO_ID)
        REFERENCES USR_GESTAO_RH.DEPARTAMENTOS (DEPARTAMENTO_ID)
);

-- Sequência para FUNCIONARIO_ID
CREATE SEQUENCE FUNCIONARIO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_FUNCIONARIO_ID
BEFORE INSERT ON USR_GESTAO_RH.FUNCIONARIOS
FOR EACH ROW
WHEN (NEW.FUNCIONARIO_ID IS NULL)
BEGIN
   :NEW.FUNCIONARIO_ID := FUNCIONARIO_SEQ.NEXTVAL;
END;
/

--------AVALIAÇÕES DE DESEMPENHO--------
CREATE TABLE USR_GESTAO_RH.AVALIACOES_DESEMPENHO (
    AVALIACAO_ID NUMBER(38, 0) NOT NULL,
    FUNCIONARIO_ID NUMBER(38, 0) NOT NULL,
    DATA_AVALIACAO DATE,
    NOTA NUMBER(4, 2),
    COMENTARIOS VARCHAR2(4000),
    CONSTRAINT PK_AVALIACOES_DESEMPENHO PRIMARY KEY (AVALIACAO_ID),
    CONSTRAINT FK_AVALIACOES_FUNCIONARIOS FOREIGN KEY (FUNCIONARIO_ID)
        REFERENCES USR_GESTAO_RH.FUNCIONARIOS (FUNCIONARIO_ID)
);
--Sequência para AVALIACAO_ID
CREATE SEQUENCE AVALIACAO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_AVALIACAO_ID
BEFORE INSERT ON USR_GESTAO_RH.AVALIACOES_DESEMPENHO
FOR EACH ROW
WHEN (NEW.AVALIACAO_ID IS NULL)
BEGIN
   :NEW.AVALIACAO_ID := AVALIACAO_SEQ.NEXTVAL;
END;
/



--------FOLHA DE PAGAMENTOP--------
CREATE TABLE USR_GESTAO_RH.FOLHA_PAGAMENTO (
    PAGAMENTO_ID NUMBER(38, 0) NOT NULL,
    FUNCIONARIO_ID NUMBER(38, 0) NOT NULL,
    DATA_PAGAMENTO DATE,
    SALARIO_BRUTO NUMBER(10, 2),
    DESCONTOS NUMBER(10, 2),
    SALARIO_LIQUIDO NUMBER(10, 2),
    CONSTRAINT PK_FOLHA_PAGAMENTO PRIMARY KEY (PAGAMENTO_ID),
    CONSTRAINT FK_PAGAMENTO_FUNCIONARIOS FOREIGN KEY (FUNCIONARIO_ID)
        REFERENCES USR_GESTAO_RH.FUNCIONARIOS (FUNCIONARIO_ID)
);

--Sequência para PAGAMENTO_ID
CREATE SEQUENCE PAGAMENTO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_PAGAMENTO_ID
BEFORE INSERT ON USR_GESTAO_RH.FOLHA_PAGAMENTO
FOR EACH ROW
WHEN (NEW.PAGAMENTO_ID IS NULL)
BEGIN
   :NEW.PAGAMENTO_ID := PAGAMENTO_SEQ.NEXTVAL;
END;
/
